lowRISC/ibex-demo-system

- .gitignore
- ibex_demo_system_core.core
- rtl/fpga/top_artya7.sv
- rtl/system/dm_top.sv
- rtl/system/gpio.sv
- rtl/system/ibex_demo_system.sv
- rtl/system/pwm.sv
- rtl/system/pwm_wrapper.sv
- sw/common/CMakeLists.txt
- sw/common/demo_system.h
- sw/common/link.ld
- sw/common/pwm.c
- sw/common/pwm.h
- sw/demo/main.c
This PR supersedes the PR that got closed when the demo system became public: https://github.com/lowRISC/ibex-demo-system/pull/2
Added pulse width modulation to RGB LEDs, which are controlled by the switches. I also added a way for the buttons to control the green LEDs.
The LEDs are very bright by default, so I had to set the default pulse width quite short. That's why the switches only control the least significant bits in the pulse width.
I could integrate this into the GPIO module if that is desired.
> [pwm] Add PWM modules to dim RGB LEDs

- .gitignore
- README.md
I'm not sure why the fusesoc --run command does not work to program the hardware for me during testing, but manually reaching in and running the generated 'make pgm' command does work, so add it as a commented suggestion.
> Move python venv to ./venv dir, add backup programming command

- data/pins_artya7.xdc
This change changes which Arty-A7 shield connector pins we plug our display into.
Currently we use pins io0-io5 to connect the display.
This changes to using pins a6-a11, which are on the opposite side of the shield.
This change is made to make the cable routing and assembly easier. Any existing devkits will need to change to the new configuration to keep working as expected.
> WIP pinout and add comments to shellHook

- sw/common/crt0.S
- sw/common/demo_system.c
- sw/common/demo_system.h
- sw/common/demo_system_regs.h
Adds simulation halting in Verilator after main program execution by adding a snippet to `crt0.S`. Same trick already exists in simple_system examples.
Signed-off-by: Canberk Topal <ctopal@lowrisc.org>
Can be tested by simply removing the `while(1)` loop in demo `main.c`, building with Verilator and see the simulation end on its own.
> [verilator] Use simctrl to halt sim after main

- sw/demo/lcd_st7735/main.c
This function should return the "number of data sent", according to the documentation in `vendor/display_drivers/core/lcd_base.h`.
Fixing this removes a compile-time warning.
> [sw] Fix return value of `spi_write`

- vendor/display_drivers/st7735/lcd_st7735.c
This fix removes a compile-time warning.
This should ideally be fixed upstream and vendored back in, but in the interest of time I propose this direct fix.  We can create an issue to track upstream resolution.
> [vendor/display_drivers] Fix return value of `lcd_st7735_set_orientation`

- data/pins_cw305.xdc
- data/pins_cw312a35.xdc
- ibex_demo_system.core
- rtl/fpga/top_cw305.sv
- rtl/fpga/top_cw312a35.sv
- sw/demo/CMakeLists.txt
- sw/demo/basic-passwdcheck/CMakeLists.txt
- sw/demo/basic-passwdcheck/README
- sw/demo/simpleserial-aes/CMakeLists.txt
- sw/demo/simpleserial-aes/README
- vendor/newae/basic-passwdcheck/basic-passwdcheck.c
- vendor/newae/crypto/aes-independant.c
- vendor/newae/crypto/aes-independant.h
- vendor/newae/crypto/tiny-AES128-C/aes.c
- vendor/newae/crypto/tiny-AES128-C/aes.h
- vendor/newae/hal/hal.h
- vendor/newae/hal/ibex/ibex_hal.c
- vendor/newae/hal/ibex/ibex_hal.h
- vendor/newae/simpleserial-aes/simpleserial-aes.c
- vendor/newae/simpleserial-ecc/simpleserial-ecc.c
- vendor/newae/simpleserial/simpleserial.c
- vendor/newae/simpleserial/simpleserial.h
This adds support for the CW305 and CW312-A35 FPGA target boards. It also includes, as examples, two applications that are used in our existing set of Jupyter notebook courses (note that applications can also be built over in ChipWhisperer land with the recent addition of the Ibex HAL there: https://github.com/newaetech/chipwhisperer/commit/1aab0059731997b862e9cf50c5d390f33ee26fed).
> Add NewAE targets and applications

- util/load_demo_system.sh
BASH_SOURCE is unset on systems with a POSIX-compatible /bin/sh, including Ubuntu.
> Fix load_demo_system.sh shebang and shell compliance

- README.md
Arty-A7 USB configuration is required for both container and native python environment
> Move Arty-A7 USB config to a separate section

- README.md
- sw/CMakeLists.txt
- sw/blank/CMakeLists.txt
- sw/common/CMakeLists.txt
- sw/demo/basic-passwdcheck/CMakeLists.txt
- sw/demo/hello_world/CMakeLists.txt
- sw/demo/lcd_st7735/CMakeLists.txt
- sw/demo/simpleserial-aes/CMakeLists.txt
- sw/gcc_toolchain.cmake
- Set the target compiler and flags in a toolchain file
- Enhance portability to other toolchains
- Enable compiler flags to be set in the CMake cache
- Use the target toolchain instead of the host toolchain for CMake compiler detection
- Enable assembly language support
- Simplify linking the common library
> [sw] Apply common CMake conventions

- python-requirements.txt
The hjson requirement is needed to run `util/vendor.py` in the virtual environment.
> Add hjson to python requirements

- flake.nix
- ibex_demo_system.core
These are some minor fixes to the software path, which I found because of a critical warning from Vivado:
```
CRITICAL WARNING: [Synth 8-4445] could not open $readmem data file '../../../../../sw/build/blank/blank.vmem'; please make sure the file is added to project and has read permission, ignoring [/home/mvdmaas/repos/demo-system-ibex/build/lowrisc_ibex_demo_system_0/src/lowrisc_prim_util_memload_0/rtl/prim_util_memload.svh:66]
```
> Fix software path

- rtl/system/dm_top.sv
- rtl/system/ibex_demo_system.sv
We use host and device for our memory bus, we should use the same in our debug module top.
> Consistently use host and device for memory bus

- .gitignore
These files are generated by Verilator when using the `-t` option. This is an example command that produces `sim.fst`:
```sh
./build/lowrisc_ibex_demo_system_0/sim-verilator/Vibex_demo_system -t --meminit=ram,$(pwd)/sw/c/build/demo/hello_world/demo
```
> Add simulation wavefile to git ignore

- rtl/system/gpio.sv
- rtl/system/ibex_demo_system.sv
- rtl/system/spi_host.sv
This is to resolve `GENUNNAMED` warnings when using Verilator version 5.018
Closes: https://github.com/lowRISC/ibex-demo-system/issues/77
> Add labels to generate blocks

- rtl/fpga/top_artya7.sv
- rtl/system/debounce.sv
- rtl/system/gpio.sv
- rtl/system/ibex_demo_system.sv
- rtl/system/pwm.sv
- rtl/system/pwm_wrapper.sv
- rtl/system/spi_host.sv
- rtl/system/spi_top.sv
- rtl/system/uart.sv
These fixes include:
- Indentation of parameter lists.
- Indentation of input/output lists.
- Indentation of variable declaration.
- Making comments full sentences ending in period.
- Adding address and data width parameters.
- Turn Verilator lints back on and resolve width and unused warnings.
- Use ANSI style of parameter declarations.
> Make formatting of RTL files consistent

- sw/rust/.cargo/config.toml
- sw/rust/Cargo.toml
- sw/rust/build.rs
- sw/rust/demo/hello_world/Cargo.toml
- sw/rust/demo/lcd_hal/Cargo.toml
- sw/rust/demo/led/Cargo.toml
- sw/rust/demo/led_hal/Cargo.toml
- sw/rust/demo/pwm_hal/Cargo.toml
This has two advantages:
1. It adds a `cargo:rerun-if-changed` command to ensure we rebuild crates if the linker script changes.
2. The path to the linker script does not depend on the directory that Cargo is executed from, so `cargo build` can be done from anywhere.
> Set linker script from build.rs file

- data/pins_sonata.xdc
This PR changes the pin of the reset button for the correct one of the V0.5 board.
This PR also contains some minor changes:
- Align the names of the clocks with the port names.
- Use dictionary for the reset button.
> Sonata v0.5 board changes

- dv/verilator/demo_system_verilator_lint.vlt
- ibex_demo_system_core.core
- WIDTHEXPAND does not exist for Verilator 4.210
- The verilator waiver file does not exist
- Added some extra lint waivers
> Fix Verilator build and lint

- .gitignore
- README.md
- dv/verilator/demo_system_verilator_lint.vlt
- dv/verilator/ibex_demo_system.cc
- dv/verilator/ibex_demo_system.h
- dv/verilator/ibex_demo_system_main.cc
- dv/verilator/top_verilator.sv
- flake.nix
- ibex_demo_system.core
- rtl/system/ibex_demo_system.sv
- vendor/lowrisc_ip.vendor.hjson
- vendor/lowrisc_ip/dv/dpi/uartdpi/uartdpi.c
- vendor/lowrisc_ip/dv/dpi/uartdpi/uartdpi.core
- vendor/lowrisc_ip/dv/dpi/uartdpi/uartdpi.h
- vendor/lowrisc_ip/dv/dpi/uartdpi/uartdpi.sv
- vendor/lowrisc_ip/dv/dpi/uartdpi/uartdpi_sv.core
Draft because it's currently sitting atop https://github.com/lowRISC/ibex-demo-system/pull/91
Recommend making the following change when testing:
```diff
diff --git a/sw/c/demo/hello_world/main.c b/sw/c/demo/hello_world/main.c
index 3d4b333..0ef4b4a 100644
--- a/sw/c/demo/hello_world/main.c
+++ b/sw/c/demo/hello_world/main.c
@@ -29,7 +29,7 @@ int main(void) {
// This indicates how often the timer gets updated.
timer_init();
-  timer_enable(5000000);
+  timer_enable(500);
uint64_t last_elapsed_time = get_elapsed_time();
```
> Integrated OpenTitan's DPI based Virtual UART into the verilator test bench

- util/sonata-olimex-openocd-cfg.tcl
We need to work out a better way to organise OpenOCD configs and stop hard-coding the config file in the `load_demo_system.sh` script. However not a priority for now so just chucking all of this in a separate new config file.
This works with the Olimex ARM-USB-TINY-H against the Sonata v0.5 board.
> [util] Add openocd to allow use of Olimex probe with Sonata

- sw/c/gcc_toolchain.cmake
Before this some build environments would use an objcopy that was not RISC-V compliant.
Closes: https://github.com/lowRISC/ibex-demo-system/issues/78
> Set objcopy to RISC-V

- python-requirements.txt
The packaging requirement is needed to run `util/check_tool_requirements.py` in the virtual environment.
> Add packaging to python requirements

- .github/workflows/cmake.yml
- .github/workflows/rust.yml
Version 3 of `actions/checkout` uses Node.js 16 which will be disabled in June. See [this blog post] for details.
[this blog post]: https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/
> [ci] Update GitHub actions for Node.js v20

- sw/rust/.cargo/config.toml
- sw/rust/rust-toolchain.toml
I don't think bitmanip is important for the demos, just thought it was interesting that you can enable them.
Happy if this doesn't get merged, but someone can use this as a reference if they need it elsewhere.
> Enable ratified bitmanip extensions for Rust demos

- util/arty-a7-openocd-cfg.tcl
- util/sonata-openocd-cfg.tcl
riscv set_prefer_sba command to use System Bus Access to access memory deprecated. 
Update use of riscv set_mem_access instead.
Updated cmds "riscv set_prefer_sba" and "riscv set_mem_access" in openocd configuration file used to flash software.
> Update openocd commands to flash software

- ibex_demo_system.core
- pulp_riscv_dbg.core
The current instructions fail to work for the demo platform when used with the native Python environment as noted in #116 as the upstream version of FuseSoC does not support tags.
This PR flips the logic surrounding the tags so that the Bscane tap is used by default as this is what is needed for most FPGA-based platforms. Sonata is the obvious exception, so a note has been added to the README.
I've based this off of #136 as that is already approved for merge.
> Change logic behind JTAG tap selection to make instrustions work for the demo platform
